apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-api
  labels:
    app: udagram-feed-api
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: udagram-feed-api