apiVersion: apps/v1
kind: Deployment
metadata:
  name: rev-proxy-deploy
  labels:
    app: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - name: rev-proxy
        image: scharati/rev-proxy:v3
        ports:
        - containerPort: 8000
