apiVersion: v1
kind: Service
metadata:
  name: rev-proxy-svc
  labels:
    service: reverse-proxy
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30002
  selector:
    app: reverse-proxy
  type: LoadBalancer