apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-users-deployment
  labels:
    app: udagram-api-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-users
  template:
    metadata:
      labels:
        app: udagram-api-users
    spec:
      containers:
      - name: udagram-api-users
        image: scharati/udagram-api-users:v1
        ports:
        - containerPort: 8081
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: udagram-configmap
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
             name: udagram-configmap
             key: POSTGRES_DB
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: udagram-configmap
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: udagram-configmap
              key: AWS_REGION
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: udagram-secret
              key: JWT_SECRET
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: udagram-configmap
              key: URL
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: udagram-configmap
              key: AWS_PROFILE              
